jest: use ESM format
Eventually, we will use some ESM-only external modules, so we will need
to run as ESM to import them.

The rollup change to start bundling `papaparse` is due to a difference
in how Node and TypeScript understand the structure of the `papaparse`
package. TypeScript uses `@types/papaparse` and accepts that there are
named exports available. Node's "CommonJS imported in ESM"
heuristic-based parser does not understand `papaparse`'s exports, so it
refuses to let named imports work.

    SyntaxError: The requested module 'papaparse' does not provide an export named 'parse'

Node will accept `const {parse} = require('papaparse');`, but TypeScript
does not seem to generate that for either `import _pp from 'papaparse';
const {parse} = _pp` (destructured imported default), or for `import *
as _pp from 'papaparse'; const {parse} = _pp;` (destructured imported
namespace). Maybe there is some combination of options or syntax that
would let both Node and TypeScript import `papaparse`, but I have not
found it.