Scriptable tool: check navigator.onLine before editions
Add an basic online check via `navigator.onLine` in a WebView before
doing GetISBNs with editions queries.

I tried reproducing the realFetcher errors I saw using fakeFetcher in a
couple of new ways:

- Making substitute requests to httpbin instead of waiting for a timer
- Making substitute requests to httpbin (for OL) and httpbun (for LT)

I tried with separately throttled services (an OL and the LT), and some
of the substitute fetches took a long time (I saw a max fetch duration
over 20s) so there were definitely overlapping requests. So the problem
didn't seem to be Scriptable limiting us to a single active request.
Also, since I added multiple substitute endpoints, the problem didn't
seem to be related to making requests to more than one origin, either.

Eventually I thought that maybe there might have been a Wi-Fi issue when
I ran the first realFetcher test (the Wi-Fi is sometimes a bit flakey
here; and it was the first time I used the device in a few hours--the
program had been iCloud synchronized the day before). Turning off the
Wi-Fi and enabling Airplane mode made the active progress numbers keep
growing beyond 10 and produced some console.errors (via rejection
report):

    Error: A data connection is not currently allowed

and

    Error: The Internet connection appears to be offline.

THe first error is probably the one I saw the first time I tried
realFetcher.